edition = "2021"
empty_item_single_line = false
format_code_in_doc_comments = true
format_macro_matchers = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
imports_indent = "Block"
match_arm_blocks = false
max_width = 80
overflow_delimited_expr = true
reorder_impl_items = true
reorder_imports = true
unstable_features = true
use_small_heuristics = "Max"
use_try_shorthand = true
